services:
  worker:
    image: ghcr.io/minerva-archive/worker:latest
    build:
      context: .
    entrypoint: ["uv", "run", "minerva"]
    environment:
      - MINERVA_SERVER
      - MINERVA_TOKEN_FILE_DIRECTORY
      - MINERVA_AUTH_HOST
      - MINERVA_AUTH_PORT
      - MINERVA_RETRIES
      - MINERVA_RETRY_DELAY
      - MINERVA_CONCURRENCY
      - MINERVA_MIN_JOB_SIZE
      - MINERVA_MAX_JOB_SIZE
      - MINERVA_HISTORY_LINES
    volumes:
      - ${HOME}/.minerva-dpn/:/root/.minerva-dpn
    restart: unless-stopped

volumes:
  data:
