services:
  worker:
    image: ghcr.io/minerva-archive/worker:latest
    build:
      context: .
    # Uncomment these if you want terminal interactivity. See the README for more info
    # stdin_open: true
    # tty: true
    # change your worker settings here:
    command: ["uv", "run", "minerva", "run"]
    environment:
      # extra settings you can change, see ./minerva/constants.py
      MINERVA_SERVER: "https://firehose.minerva-archive.org"
      MINERVA_TOKEN_FILE: "/root/.minerva-dpn/token"
      MINERVA_RETRIES: 3
      MINERVA_RETRY_DELAY: 5
      MINERVA_HISTORY_LINES: 5
      MINERVA_CONCURRENCY: 10
    volumes:
      - ${HOME}/.minerva-dpn/:/root/.minerva-dpn

volumes:
  data:
